;;; package --- Main init file
;;; Commentary:
;;; This is my init file
;;; Generated by Tim de Jong on December 18th using emacs-bootstrap.com

;;; Code:

(add-to-list 'load-path (concat user-emacs-directory "elisp"))

(require 'base)
(require 'base-theme)
(require 'base-extensions)
(require 'base-functions)
(require 'base-global-keys)

(require 'lang-python)

(require 'lang-javascript)

(require 'lang-web)
